# Generated by Django 5.1.5 on 2025-02-08 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentscript_scriptpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscript',
            name='subject_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
            preserve_default=False,
        ),
    ]
