# Generated by Django 5.1.5 on 2025-02-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_studentscript_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentscript',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
