# Generated by Django 5.1.5 on 2025-02-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_subject_id_studentscript_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptpage',
            name='page_nummber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
