# Generated by Django 5.1.5 on 2025-02-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_scriptpage_page_nummber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scriptpage',
            old_name='page_nummber',
            new_name='page_number',
        ),
    ]
