# Generated by Django 5.1.5 on 2025-02-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_page_nummber_scriptpage_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptpage',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
