# Generated by Django 5.1.5 on 2025-02-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_scriptpage_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptpage',
            name='extracted_answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
