# Generated by Django 5.1.5 on 2025-03-04 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('app', '0009_scriptpage_extracted_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True, null=True)),
                ('student_score', models.IntegerField(blank=True, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('attempted', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subjectquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResultScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_score', models.IntegerField(blank=True, null=True)),
                ('percentage_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('is_disabled', models.BooleanField(default=True)),
                ('effective_total_marks', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
