# Generated by Django 5.1.5 on 2025-04-29 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_examresult_examresultscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='app.exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresultscore',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_scores', to='app.exam'),
            preserve_default=False,
        ),
    ]
