# Generated by Django 5.1.5 on 2025-08-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_examresult_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectquestion',
            name='comprehension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectquestion',
            name='examiner_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectquestion',
            name='question',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='subjectquestion',
            name='question_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
